name: instagram_clone
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.13.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_staggered_grid_view: 0.4.0
  video_player: 2.4.5
  expandable_text: 2.3.0
  marquee: 2.2.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy-Regular.ttf
  uses-material-design: true
